export const Login_API = "login.php";
export const Category_API = "category.php";
export const Product_API = "product.php";
export const Cart_API = "cart.php";
export const Occasion_API="occasion.php";
export const Register_API="register.php";
export const ValidateRegister_API="validate.php";
export const ForgetPass_API="forgetpass.php";
export const Profile_API="profile.php";
